[package]
name = "mikisayaka"
version = "2025.3.2"
edition = "2021"
build = "build.rs"

[dependencies]
anyhow = "1.0.86"
chrono = "0.4.38"
dotenvy = "0.15.7"
fancy-regex = "0.14.0"
futures = "0.3.31"
mangadex-api = { version = "3.4.1", features = ["multi-thread", "tokio-multi-thread"] }
mangadex-api-schema-rust = "0.10.0"
mangadex-api-types-rust = "0.10.0"
poise = { version = "0.6.1", features = ["cache"] }
rand = "0.8.5"
reqwest = "0.12.12"
rustc_version_runtime = "0.3.0"
sea-orm = { version = "1.0.1", features = [
    "macros",
    "runtime-tokio-rustls",
    "sqlx-sqlite",
    "with-time",
    "with-uuid",
], default-features = false }
sea-orm-migration = { version = "1.0.0", features = [
    "with-time",
    "sqlx-sqlite",
    "runtime-tokio-rustls",
    "with-uuid",
], default-features = false }
semver = "1.0.23"
serde = { version = "1.0.218", features = ["serde_derive"] }
time = "0.3.36"
tokio = { version = "1.39.2", features = ["rt-multi-thread", "tracing"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
urlencoding = "2.1.3"
uuid = "1.10.0"

[build-dependencies]
anyhow = "1.0.86"
vergen-gitcl = "1.0.0"
