[package]
name = "mikisayaka"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
anyhow = "1.0.86"
dotenvy = "0.15.7"
poise = "0.6.1"
rustc_version_runtime = "0.3.0"
semver = "1.0.23"
tokio = { version = "1.39.2", features = ["rt-multi-thread", "tracing"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[build-dependencies]
anyhow = "1.0.86"
vergen-gitcl = "1.0.0"
