services:
    mikisayaka:
        hostname: mikisayaka
        container_name: mikisayaka
        build:
            dockerfile: Dockerfile
        volumes:
            - ./database:/app/database:rw
        env_file:
            - .env
        restart: unless-stopped

    grafana-alloy:
        image: grafana/alloy:latest
        container_name: grafana-alloy
        restart: unless-stopped
        ports:
            - "12345:12345"
        volumes:
            - ./config.alloy:/etc/alloy/config.alloy:ro
            - /var/log:/var/log:ro
        command: 
            - run
            - /etc/alloy/config.alloy
            - --server.http.listen-addr=0.0.0.0:12345
            - --storage.path=/tmp/alloy
            - --stability.level=public-preview
        environment:
            - ALLOY_LOG_LEVEL=info
